import { DownloadInvestorDeckSection } from './download-investor-deck-section';
import { TractionSection } from './traction-section';
import { HeroSection } from './hero-section';
import { HeaderSection } from './header-section';
import { StatisticSection } from './statistic-section';
import { ReasonsToInvestSection } from './reasons-to-invest-section';
import { RevenueSection } from './revenue-projections-section';
import { MilestonesSection } from './milestones-section';
import { AwardsSection } from './awards-section';
import { FeaturedOnSection } from './featured-on-section';
import { PressAboutUsSection } from './press-about-us-section';
import { ProblemSolutionSection } from './problem-solution-section';
import { HowItWorksSection } from './how-it-works-section';
import { CompetitionSection } from './competition-section';
import { MarketHugeSection } from './market-huge-section';
import { MarketStructureSection } from './market-structure-section';
import { OurBusinessModelSection } from './our-business-model-section';
import { InstallationsSection } from './installations-section';

export { HeaderSection, HeroSection, StatisticSection, ReasonsToInvestSection, TractionSection, RevenueSection, MilestonesSection , AwardsSection, DownloadInvestorDeckSection, FeaturedOnSection, PressAboutUsSection, ProblemSolutionSection, HowItWorksSection, CompetitionSection, MarketHugeSection, MarketStructureSection, OurBusinessModelSection, InstallationsSection};
